

<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Login_pustu extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		$this->load->model('Obat_model');
	}

	public function index()
	{
		if($this->session->userdata('logined1') == true)// userdata itu penampung session. logined nama session && $this->session->userdata('logined')
		{
			redirect('Pustu');
		}

	if(!$this->input->post())
	{
		$this->load->view('Login_pustuform');
	}
	else
	{
		$cek_login2=$this->Obat_model->cek_login2($this->input->post('username'),$this->input->post('password'));
		if (!empty($cek_login2)) {
				$this->session->set_userdata('username',$cek_login2->nama_pustu);
				$this->session->set_userdata('id_login',$cek_login2->id_pustu); 
				$this->session->set_userdata('logined1', true);
				redirect('Pustu');
			}
			
			else 
			{
				redirect("/Login_pustu");
			}
		}

	} 
	
	public function Logoutuser()
	{
		$this->session->unset_userdata('logined1');// unset itu menghapus isi session di userdata
		redirect("/Login_pustu");
	} 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */