<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Login extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		$this->load->model('Obat_model');
	}

	public function index()
	{
		if($this->session->userdata('logined') == true)// userdata itu penampung session. logined nama session && $this->session->userdata('logined')
		{
			redirect('Obat');
		}

	if(!$this->input->post())
	{
		$this->load->view('Login');
	}
	else
	{

		$cek_login=$this->Obat_model->cek_login($this->input->post('username'),$this->input->post('password'));
		if(!empty($cek_login))
		{
				$this->session->set_userdata('username',$cek_login->nama_admin); // set untuk me set
				$this->session->set_userdata('logined', true);
				
				redirect('Obat');
			}
			
			else 
			{
				redirect("/");
			}
		}

	} 
	
	public function logout()
	{
		$this->session->unset_userdata('logined');// unset itu menghapus isi session di userdata
		redirect("/");
	} 
	public function Logoutuser()
	{
		$this->session->unset_userdata('logined1');// unset itu menghapus isi session di userdata
		redirect("/");
	} 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */